name = "VetFun"
uuid = "5b28ad16-e89d-4e7d-854d-6d28c5ecdfd2"
authors = ["Sven Duve"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
